// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NecklaceDB;

#nullable disable

namespace NecklaceDB.Migrations
{
    [DbContext(typeof(NecklaceDbContext))]
    [Migration("20220317083736_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NecklaceModels.Necklace", b =>
                {
                    b.Property<int>("NecklaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NecklaceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NecklaceID"), 1L, 1);

                    b.HasKey("NecklaceID");

                    b.ToTable("Necklaces");
                });

            modelBuilder.Entity("NecklaceModels.Pearl", b =>
                {
                    b.Property<int>("PearlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PearlID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PearlID"), 1L, 1);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("NecklaceID")
                        .HasColumnType("int")
                        .HasColumnName("NecklaceID");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("PearlID");

                    b.HasIndex("NecklaceID");

                    b.ToTable("Pearls");
                });

            modelBuilder.Entity("NecklaceModels.Pearl", b =>
                {
                    b.HasOne("NecklaceModels.Necklace", "Necklace")
                        .WithMany("Pearls")
                        .HasForeignKey("NecklaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Necklace");
                });

            modelBuilder.Entity("NecklaceModels.Necklace", b =>
                {
                    b.Navigation("Pearls");
                });
#pragma warning restore 612, 618
        }
    }
}
